appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: sEE0DQrKDLV7U1qOoYehcyCX9Vv5280NHDwfheHmB330N59727DxbwNrVZTNx3+R9cG5PX9gzunM1xZDJW4/uQLE5LL2q3kOvyF9OPBuRFam1YTEvO4ny2cP/asjSz3hwa3PH+Kd7wBlXUMQmmluledY55pXC5SJ8suqKI0etoJ8S+CZWE9HwbMSWEr2tgs9xov+6x88ZpsYDCfDR0gX3ATTChbOH3dFLHBBbKGUQj1eI46Sm/bx7vItt2bpR+xE5D8br5yHCci29GIeoF4V3kwnxr5hZu3X7DKKET0Iah+lzt3D/YEHP12/LRpkizSw5co9Bszhb+l/oR8DQEvjpirSIgN/rhY7gZty+bRBYOC3pAeBxPSLdbPP2Q/gKLoQ+8wn9qVRZeTeAzub83+8g+g35aoWabAYYq2G8AgVgoOLwGYotXdiofNltHaJfNGPziXjHE4heHZ9ROVucpgXWrDd2TS1SpwlLtnyL1m++xkmlGW5cMvSiskJREs7wDJtHTEFyglIF+4U6jVBL2I9Kop1Ncbba43QhhzxQyWWjSM876/fAsm6Vg5cPA6a8dIWv8rB9dUxuGWaMZ/hZrjYTJAsVSMCoW3YsW3mqY8J5uDgJz4pPW8jfzdSaJnD2DEWrxwI6FYVCbYpTkzIdu6dK3bOE9dgvXsaRCPXlF14UKo=}
